name: webviewx_plus
description: A cross-platform webview using webview_flutter for
  mobile and iFrame for web.
repository: https://github.com/Mahad61/webviewx_plus
version: 0.7.0+2

platforms:
  android:
  ios:
  web:


environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  path: ^1.9.1
  pointer_interceptor: ^0.10.1+2
  uuid: ^4.5.1
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.7.0
  webview_flutter_platform_interface: ^2.13.0
  webview_flutter_wkwebview: ^3.22.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
